name: Fullstack Build (Angular + .NET)

on:
  push:
    branches:
      - main

jobs:

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task-frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: task-frontend/dist/task-frontend


  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 🔥 CLEAN EVERYTHING (fixes your error)
      - name: Clean project
        run: dotnet clean TaskApi/TaskApi.csproj

      # 🔥 RESTORE PROPERLY
      - name: Restore
        run: dotnet restore TaskApi/TaskApi.csproj

      # 🔥 BUILD WITHOUT SKIPPING
      - name: Build
        run: dotnet build TaskApi/TaskApi.csproj --configuration Release

      # 🔥 PUBLISH
      - name: Publish
        run: dotnet publish TaskApi/TaskApi.csproj -c Release -o publish

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: publish