name: Fullstack Build (Angular + .NET)

on:
  push:
    branches:
      - main

jobs:

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task-frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: task-frontend/dist/task-frontend


  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 🔥 DEBUG: Show folder structure
      - name: Show Project Structure
        run: ls -R

      - name: Setup .NET (all versions safe)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Show .NET Info
        run: dotnet --info

      - name: Restore Dependencies
        run: dotnet restore TaskApi/TaskApi.csproj

      # 🔥 IMPORTANT: detailed logs
      - name: Build Project (detailed logs)
        run: dotnet build TaskApi/TaskApi.csproj --configuration Release --no-restore --verbosity detailed

      - name: Publish Project
        run: dotnet publish TaskApi/TaskApi.csproj -c Release -o publish --no-build

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: publish