name: Fullstack Build (Angular + .NET)

on:
  push:
    branches:
      - main

jobs:

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task-frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: task-frontend/dist


   backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Clean
        run: rm -rf TaskApi/obj TaskApi/bin

      - name: Restore
        run: dotnet restore TaskApi/TaskApi.csproj

      - name: Build
        run: dotnet build TaskApi/TaskApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish TaskApi/TaskApi.csproj -c Release -o publish

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: publish/